// <auto-generated />
using System;
using BookCatalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookCatalog.Infrastructure.Migrations
{
    [DbContext(typeof(BookCatalogDbContext))]
    [Migration("20260909171117_Add Loans")]
    partial class AddLoans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookCatalog.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Id");

                    b.ToTable("Authors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Authors_Name_NotBlank", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("BookCatalog.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.HasIndex("Title", "Id");

                    b.ToTable("Books", null, t =>
                        {
                            t.HasCheckConstraint("CK_Books_PublicationYear_Minimum", "\"PublicationYear\" >= 1450");
                        });
                });

            modelBuilder.Entity("BookCatalog.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BorrowedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique()
                        .HasDatabaseName("IX_Loans_BookId_Active")
                        .HasFilter("\"ReturnedAt\" IS NULL");

                    b.HasIndex("BookId", "BorrowedAt", "Id")
                        .IsDescending(false, true, true);

                    b.HasIndex("UserId", "BorrowedAt", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("Loans", null, t =>
                        {
                            t.HasCheckConstraint("CK_Loans_ReturnedAt_AfterBorrowedAt", "\"ReturnedAt\" IS NULL OR \"ReturnedAt\" >= \"BorrowedAt\"");
                        });
                });

            modelBuilder.Entity("BookCatalog.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName", "Id");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_DisplayName_NotBlank", "btrim(\"DisplayName\") <> ''");
                        });
                });

            modelBuilder.Entity("BookCatalog.Domain.Entities.Book", b =>
                {
                    b.HasOne("BookCatalog.Domain.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookCatalog.Domain.Entities.Loan", b =>
                {
                    b.HasOne("BookCatalog.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Loans_Books_BookId");

                    b.HasOne("BookCatalog.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Loans_Users_UserId");

                    b.Navigation("Book");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
